### ISSUE TITLE
How to setup on Ubuntu 18.04

### ISSUE THREAD

**Issue by arjunskumar** [yishuolin/notion-leetcode-clipper#4]
Any solutions to make it work on Ubuntu 18.04

**Comment by yishuolin** [comment]
Hi, I'm sorry that I only tested it on Mac. At which step did you encounter problems?

**Comment by arjunskumar** [comment]
@yishuolin When I try `yarn build`
I'm getting this
```
yarn run v1.22.15
warning package.json: No license field
$ webpack --config ./webpack/webpack.config.js
/home/arjun/Desktop/notion-leetcode-clipper/node_modules/p-limit/index.js:29
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/terser-webpack-plugin/dist/index.js:18:38)
    at Module._compile (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/terser-webpack-plugin/dist/cjs.js:3:16)
    at Module._compile (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/arjun/Desktop/notion-leetcode-clipper/webpack/webpack.config.js:2:22)
    at Module._compile (/home/arjun/Desktop/notion-leetcode-clipper/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by yishuolin** [comment]
@arjunskumar  Chances are that you need to upgrade you `node` to support `catch` syntax. You can check your `node` version by `node -v`. FYI, my version is `v14.17.6`.

**Comment by arjunskumar** [comment]
I have installed the correct node version `sudo tar -xf node-v14.17.6-linux-x64.tar.xz --directory=/usr/local --strip-components=1`

This is my log for yarn build

```
arjun@arjun:~/Desktop/notion-leetcode-clipper$ yarn build
yarn run v1.22.15
warning package.json: No license field
$ webpack --config ./webpack/webpack.config.js
assets by path *.js 26.6 KiB
  asset popup.js 26.4 KiB [emitted] [minimized] (name: popup)
  asset content.js 232 bytes [emitted] [minimized] (name: content)
asset popup.html 706 bytes [emitted]
asset manifest.json 569 bytes [emitted] [from: manifest.json] [copied]
orphan modules 3.7 KiB [orphan] 4 modules
runtime modules 663 bytes 3 modules
modules by path ./node_modules/axios/ 49 KiB
  modules by path ./node_modules/axios/lib/ 47 KiB 27 modules
  ./node_modules/axios/index.js 40 bytes [built] [code generated]
  ./node_modules/axios/package.json 1.92 KiB [built] [code generated]
modules by path ./node_modules/style-loader/dist/runtime/*.js 5.75 KiB 6 modules
modules by path ./src/ 9.96 KiB
  ./src/js/popup.js + 4 modules 6.94 KiB [built] [code generated]
  ./src/js/content.js + 1 modules 713 bytes [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./src/css/popup.css 2.32 KiB [built] [code generated]
modules by path ./node_modules/css-loader/dist/runtime/*.js 2.33 KiB
  ./node_modules/css-loader/dist/runtime/noSourceMaps.js 64 bytes [built] [code generated]
  ./node_modules/css-loader/dist/runtime/api.js 2.27 KiB [built] [code generated]
webpack 5.54.0 compiled successfully in 820 ms
Done in 1.32s.
```

Now I'm unable to select the `Tags menu`
![error_1](https://user-images.githubusercontent.com/61345951/143820329-7a5bbe4c-768b-4b95-84d0-dedaa4f94e94.png)
g

**Comment by arjunskumar** [comment]
@yishuolin Whenever I clicked the `create` button I'm getting this error
![error_2](https://user-images.githubusercontent.com/61345951/143896115-07811499-9d2f-4c78-b531-3194a602db50.png)

**Comment by yishuolin** [comment]
> I have installed the correct node version `sudo tar -xf node-v14.17.6-linux-x64.tar.xz --directory=/usr/local --strip-components=1`
> 
> This is my log for yarn build
> 
> ```
> arjun@arjun:~/Desktop/notion-leetcode-clipper$ yarn build
> yarn run v1.22.15
> warning package.json: No license field
> $ webpack --config ./webpack/webpack.config.js
> assets by path *.js 26.6 KiB
>   asset popup.js 26.4 KiB [emitted] [minimized] (name: popup)
>   asset content.js 232 bytes [emitted] [minimized] (name: content)
> asset popup.html 706 bytes [emitted]
> asset manifest.json 569 bytes [emitted] [from: manifest.json] [copied]
> orphan modules 3.7 KiB [orphan] 4 modules
> runtime modules 663 bytes 3 modules
> modules by path ./node_modules/axios/ 49 KiB
>   modules by path ./node_modules/axios/lib/ 47 KiB 27 modules
>   ./node_modules/axios/index.js 40 bytes [built] [code generated]
>   ./node_modules/axios/package.json 1.92 KiB [built] [code generated]
> modules by path ./node_modules/style-loader/dist/runtime/*.js 5.75 KiB 6 modules
> modules by path ./src/ 9.96 KiB
>   ./src/js/popup.js + 4 modules 6.94 KiB [built] [code generated]
>   ./src/js/content.js + 1 modules 713 bytes [built] [code generated]
>   ./node_modules/css-loader/dist/cjs.js!./src/css/popup.css 2.32 KiB [built] [code generated]
> modules by path ./node_modules/css-loader/dist/runtime/*.js 2.33 KiB
>   ./node_modules/css-loader/dist/runtime/noSourceMaps.js 64 bytes [built] [code generated]
>   ./node_modules/css-loader/dist/runtime/api.js 2.27 KiB [built] [code generated]
> webpack 5.54.0 compiled successfully in 820 ms
> Done in 1.32s.
> ```
> 
> Now I'm unable to select the `Tags menu`

You will need to duplicate the [template](https://www.notion.so/yslin9901/8623ce46421a49e7bdfc449a334f08b4?v=631f11b5d34f451984a0faf593ff830c)(seems like you've solved it).
The reason why is that to make the program more responsive, `tags` are not hard-coded. Instead, they are automatically generated so that when you add/remove tags in Notion,  `tags` in your extension will update accordingly.

**Comment by yishuolin** [comment]
> Whenever I clicked the `create` button I'm getting this error

`401 unauthorized` means it lacks valid authentication credentials to make the request.

Please make sure that 
1. You have duplicated the database(STEP 1). You can not use the original database because it is not editable. 
2. You have configured your Notion integration properly(STEP 2).
3. Your **NOTION_KEY** and **NOTION_DATABASE_ID** are set(STEP 4). It will be something like
```javascript
const NOTION_KEY = 'secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
const NOTION_DATABASE_ID = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
```

Let me know if it still can not work, thank you.

**Comment by arjunskumar** [comment]
Thanks, @yishuolin for your patience in explaining. It was my mistake as I was adding page DB URL instead of workspace DB
