### ISSUE TITLE
Webpack build failing with error code Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by BhargavSushant** [yishuolin/notion-leetcode-clipper#5]
Issue raised when yarn build 

```
 yarn build
yarn run v1.22.21
warning package.json: No license field
warning ..\..\..\package.json: No license field
$ webpack --config ./webpack/webpack.config.js
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\lib\util\createHash.js:155:18)
    at BulkUpdateDecorator.update (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\lib\util\createHash.js:46:50)
    at RawSource.updateHash (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack-sources\lib\RawSource.js:77:8)
    at NormalModule._initBuildHash (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\lib\NormalModule.js:888:17)
    at handleParseResult (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\lib\NormalModule.js:954:10)
    at F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\lib\NormalModule.js:1048:4
    at processResult (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\lib\NormalModule.js:763:11)
    at F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\lib\NormalModule.js:827:5
    at F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at Array.<anonymous> (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\loader-runner\lib\LoaderRunner.js:223:4)
    at runCallbacks (F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:27:15)     
    at F:\JS\LeetcodeClipper\notion-leetcode-clipper\notion-leetcode-clipper\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:200:4
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by BhargavSushant** [comment]
> SOLVED : 
issue was caused by upgraded version of Node I was using, in newer versions of Node (17+) supports openssl 3.0+ so in order to support previous version run following command.

`export NODE_OPTIONS=--openssl-legacy-provider`

Sources  : 
https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382
https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
https://github.com/vercel/next.js/issues/30078
